# Generated by Django 5.2 on 2025-04-06 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(unique=True)),
                ('question_text', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('textbox_input', 'Textbox Input'), ('multiple_choice', 'Multiple Choice'), ('single_choice', 'Single Choice'), ('range_input', 'Range Input')], max_length=20)),
                ('options', models.JSONField(blank=True, null=True)),
                ('is_number_specific', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='MealTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('carbs', models.FloatField()),
                ('fats', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_tracking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_time_period_weeks', models.PositiveIntegerField()),
                ('plan_stages', models.JSONField()),
                ('user_height', models.CharField(max_length=20)),
                ('user_current_weight', models.CharField(max_length=20)),
                ('user_desired_weight', models.CharField(max_length=20)),
                ('user_bmi', models.FloatField()),
                ('user_favorite_foods', models.JSONField()),
                ('user_self_assessed_health', models.CharField(max_length=20)),
                ('user_health_risks', models.JSONField()),
                ('user_dietary_recommendations', models.JSONField()),
                ('user_predicted_calorie_needs', models.CharField(max_length=50)),
                ('plan_goals', models.JSONField()),
                ('potential_challenges', models.JSONField()),
                ('motivational_tips', models.JSONField()),
                ('recommended_nutrients', models.JSONField()),
                ('suggested_supplements', models.JSONField()),
                ('monitoring_metrics', models.JSONField()),
                ('success_indicators', models.JSONField()),
                ('weekly_check_in_goals', models.JSONField()),
                ('social_support_recommendations', models.JSONField()),
                ('long_term_maintenance_strategies', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('current_height', models.CharField(max_length=20)),
                ('current_weight', models.CharField(max_length=20)),
                ('desired_height', models.CharField(max_length=20)),
                ('desired_weight', models.CharField(max_length=20)),
                ('favorite_foods', models.JSONField()),
                ('self_assessed_health', models.CharField(max_length=20)),
                ('personal_touch_preference', models.BooleanField(default=False)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('health_risks', models.TextField(blank=True, null=True)),
                ('dietary_recommendations', models.TextField(blank=True, null=True)),
                ('predicted_calorie_needs', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_unit', models.CharField(choices=[('metric', 'Metric'), ('imperial', 'Imperial')], default='imperial', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_calories', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_carbs', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_consumption', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meals', models.JSONField()),
                ('total_calories', models.FloatField()),
                ('total_protein', models.FloatField()),
                ('total_carbs', models.FloatField()),
                ('total_fats', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to=settings.AUTH_USER_MODEL)),
                ('nutrition_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to='meals.nutritionplan')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserOnboardingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.onboardingquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
